# Generated by Django 2.1.7 on 2019-04-07 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[
                 ('Male', 'male'), ('Female', 'female'), ('Other', 'other')], default='Other', max_length=20)),
                ('uid', models.CharField(max_length=120)),
                ('image', models.ImageField(null=True, upload_to='student')),
                ('mobile', models.CharField(max_length=11)),
                ('alternate_mobile', models.CharField(max_length=11)),
                ('father_name', models.CharField(max_length=120)),
                ('mother_name', models.CharField(max_length=120)),
                ('temperory_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_authrise', models.BooleanField(default=False)),
                ('authrised_by', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEducationalQualifications',
            fields=[
                ('studentpersonaldetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                               primary_key=True, serialize=False, to='StudentPanel.StudentPersonalDetail')),
                ('high_school_name', models.CharField(max_length=125)),
                ('high_school_board', models.CharField(max_length=25)),
                ('inter_school_name', models.CharField(max_length=25)),
                ('inter_school_board', models.CharField(max_length=25)),
                ('bachlors_collage_name', models.CharField(max_length=25)),
                ('pg_collage_name', models.CharField(max_length=25)),
                ('highschool_grade', models.CharField(
                    default='Null', max_length=10)),
                ('highschool_obtain_marks', models.CharField(max_length=20)),
                ('highschool_max_marks', models.CharField(max_length=20)),
                ('inter_grade', models.CharField(default='Null', max_length=120)),
                ('inter_obtain_marks', models.CharField(max_length=20)),
                ('inter_max_marks', models.CharField(max_length=20)),
                ('bachalors_pursuing', models.CharField(max_length=20)),
                ('bachalors_obtain_marks', models.CharField(max_length=120)),
                ('bachalors_max_marks', models.CharField(max_length=120)),
                ('pg_pursuing', models.CharField(max_length=20)),
                ('pg_obtain_marks', models.CharField(max_length=20)),
                ('pg_total_marks', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentJobApplicationDetail',
            fields=[
                ('studentpersonaldetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                               primary_key=True, serialize=False, to='StudentPanel.StudentPersonalDetail')),
                ('skills', models.CharField(choices=[('SOFTWERE DEVELOPER', 'Softwere Developer'), ('HARDWERE DEVELOPER', 'Hardwere Developer'), (
                    'WEB DEVELOPER', 'Web Developer'), ('CIVIL ENGINEER', 'Civil Engineer')], max_length=120)),
                ('achievement', models.CharField(max_length=120)),
                ('resume', models.FileField(null=True, upload_to='stu_resume')),
            ],
        ),
        migrations.AddField(
            model_name='studentpersonaldetail',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
