# Generated by Django 2.1.7 on 2019-04-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentPanel', '0001_initial'),
        ('EmployerPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), (
                    'INPROCESS', 'Inprocess'), ('INTERVIEW SCHEDULED', 'Interview Scheduled'), ('ONHOLD', 'Onhold')], max_length=20)),
                ('skills', models.CharField(max_length=121)),
                ('achievement', models.CharField(max_length=12)),
                ('resume', models.CharField(max_length=12)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('jobpost', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='EmployerPanel.JobPost')),
                ('student', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentPanel.StudentPersonalDetail')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('changes_on', models.DateTimeField()),
                ('comment', models.CharField(max_length=120)),
                ('changes_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='EmployerPanel.Employer')),
            ],
        ),
    ]
