# Generated by Django 2.1.7 on 2019-05-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(null=True, upload_to='resume_job_application'),
        ),
    ]
