# Generated by Django 2.1.5 on 2019-04-07 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployerPanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_details',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='EmployerPanel.CompanyDetails'),
        ),
    ]
